apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: calc-dev-mongo-backup-job
spec:
#Cron Time is set according to server time, ensure server time zone and set accordingly.
  schedule: "0 8 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: calc-dev-mongo-backup-job-pod
            image: registry.abetalife.com/mongo-backup
            env:
              - name: URI
                value: ""
              - name: AWS_ACCESS_KEY_ID
                value: ""
              - name: AWS_SECRET_ACCESS_KEY
                value: ""
              - name: APP_SLACK_WEBHOOK
              - name: S3_HOST
                value: "ams3.digitaloceanspaces.com"
              - name: S3_BUCKET
                value: "s3://siz-storage/mongo_backup/"
              - name: ARCHIVE_NAME
                value: ""
            imagePullPolicy: Always
          imagePullSecrets:
            - name: regcred
          restartPolicy: OnFailure
      backoffLimit: 3
